num_classes = 11
params_fasterrcnn_resnet50_fpn = {'BATCH_SIZE': 32,
                                  'LR': 0.001,
                                  'PRECISION': 32,
                                  'CLASSES': num_classes,
                                  'SEED': 42,
                                  'PROJECT': 'Heads',
                                  'EXPERIMENT': 'heads',
                                  'MAXEPOCHS': 500,
                                  'BACKBONE': 'fasterrcnn_resnet50_fpn',
                                  'FPN': False,
                                  'ANCHOR_SIZE': ((32, 64, 128, 256, 512),),
                                  'ASPECT_RATIOS': ((0.5, 1.0, 2.0),),
                                  'MIN_SIZE': 1024,
                                  'MAX_SIZE': 1024,
                                  'IMG_MEAN': [0.485, 0.456, 0.406],
                                  'IMG_STD': [0.229, 0.224, 0.225],
                                  'I'
                                  'OU_THRESHOLD': 0.5
                                  }
params_resnet18 = {'BATCH_SIZE': 32,
                   'LR': 0.001,
                   'PRECISION': 32,
                   'CLASSES': num_classes,
                   'SEED': 42,
                   'PROJECT': 'Heads',
                   'EXPERIMENT': 'heads',
                   'MAXEPOCHS': 500,
                   'BACKBONE': 'resnet18',
                   'ANCHOR_SIZE': ((32, 64, 128, 256, 512),),
                   'ASPECT_RATIOS': ((0.5, 1.0, 2.0),),
                   'MIN_SIZE': 1024,
                   'MAX_SIZE': 1024,
                   'IMG_MEAN': [0.485, 0.456, 0.406],
                   'IMG_STD': [0.229, 0.224, 0.225],
                   'IOU_THRESHOLD': 0.5
                   }

params_mobilenet_v3_large = {'BATCH_SIZE': 32,
                             'LR': 0.001,
                             'PRECISION': 32,
                             'CLASSES': num_classes,
                             'SEED': 42,
                             'PROJECT': 'Heads',
                             'EXPERIMENT': 'heads',
                             'MAXEPOCHS': 500,
                             'BACKBONE': 'mobilenet_v3_large',
                             'ANCHOR_SIZE': ((32, 64, 128, 256, 512),),
                             'ASPECT_RATIOS': ((0.5, 1.0, 2.0),),
                             'MIN_SIZE': 1024,
                             'MAX_SIZE': 1024,
                             'IMG_MEAN': [0.485, 0.456, 0.406],
                             'IMG_STD': [0.229, 0.224, 0.225],
                             'IOU_THRESHOLD': 0.5
                             }

params_densenet121 = {'BATCH_SIZE': 32,
                      'LR': 0.001,
                      'PRECISION': 32,
                      'CLASSES': num_classes,
                      'SEED': 42,
                      'PROJECT': 'Heads',
                      'EXPERIMENT': 'heads',
                      'MAXEPOCHS': 500,
                      'BACKBONE': 'densenet121',
                      'ANCHOR_SIZE': ((32, 64, 128, 256, 512),),
                      'ASPECT_RATIOS': ((0.5, 1.0, 2.0),),
                      'MIN_SIZE': 1024,
                      'MAX_SIZE': 1024,
                      'IMG_MEAN': [0.485, 0.456, 0.406],
                      'IMG_STD': [0.229, 0.224, 0.225],
                      'IOU_THRESHOLD': 0.5
                      }